matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - pytest

    - language: cpp
      compiler: gcc
      before_script:
        - cd cpp
        - mkdir build
        - cd build
        - cmake ..
      script:
        - make