matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - pytest

    - language: cpp
      compiler: gcc
      before_script:
        - cd cpp/p001
      script:
        gcc -o p001 p001.cpp